### PR TITLE
chore: Bootstrap the mender-server repository source code

### PR DESCRIPTION
**Pull request by alfrunes**
Run `bootstrap.sh` to bootstrap the server component source code and updating the build/test environment for container images.

### CODE REVIEW

**Review by kjaskiewiczz — APPROVED** [review]
let's do it!

**Review by merlin-northern — APPROVED** [review]
what do we do with the open PRs? the best time to do this is at the begining of the sprint?

**Comment by alfrunes** [comment]
> what do we do with the open PRs? the best time to do this is at the begining of the sprint?

Do you think you could generate a patch and just add prefixes to all the path entries? :thinking:

**Comment by merlin-northern** [comment]
> > what do we do with the open PRs? the best time to do this is at the begining of the sprint?
> 
> Do you think you could generate a patch and just add prefixes to all the path entries? 🤔

sooner I would merge to original repos the open PRs and then create a PR to this repo by overriding all the files. or maybe we could run boot strap again after all the open PRs are meged to the old repos.

**Pull request merged**
