### PR TITLE
Use utils from nt-gui

### PR DESCRIPTION
**Pull request by aleksandrychev**

### CODE REVIEW

**Review by mzedel — CHANGES_REQUESTED** [review]
Thank you, I like it a lot! can you please also remove the helpers.js? just to be sure there's no leftover reference possible 🙃

**Comment by aleksandrychev** [comment]
> Thank you, I like it a lot! can you please also remove the helpers.js? just to be sure there's no leftover reference possible 🙃

yes, sure. I missed this one. I thought that I was removed together with utils/*

**Review by mzedel — APPROVED** [review]
🚀 - also FYI @olehermanse

**Comment by aleksandrychev** [comment]
I additionally tested UI manually, seems like everything is correct. so, going to merge it

**Pull request merged**
