### PR TITLE
test(deployments): listing deployments v2 endpoint test.

### PR DESCRIPTION
**Pull request by merlin-northern**
test(deployments): listing deployments v2 endpoint test.

Changelog: None
Ticket: MEN-7542
Signed-off-by: Peter Grzybowski <peter@northern.tech>

### CODE REVIEW

**Comment by merlin-northern** [comment]
@kjaskiewiczz please review only the last commit. rest you know ;-)

**Review by kjaskiewiczz — APPROVED** [review]
nice!

**Comment by kjaskiewiczz** [comment]
@merlin-northern remember to wait for PR with actual endpoint

**Comment by merlin-northern** [comment]
> @merlin-northern remember to wait for PR with actual endpoint

thank you!
wait, so I dont just merge-merge-merge?!

**Comment by merlin-northern** [comment]
> nice!

thank you!

**Pull request merged**
