### PR TITLE
Port MEN-7478 to mender-server repository

### PR DESCRIPTION
**Pull request by alfrunes**
Original PR: https://github.com/mendersoftware/iot-manager/pull/298

### CODE REVIEW

**Review by merlin-northern — APPROVED** [review]
this was rough; the patch looks really different than the one in the other repo, strange.  but it is the same I believe.

**Comment by alfrunes** [comment]
> this was rough; the patch looks really different than the one in the other repo, strange. but it is the same I believe.

Hmm... :thinking: There were no friction doing the cherry-picks. Maybe you missed the last force push in the original PR?

**Comment by merlin-northern** [comment]
> > this was rough; the patch looks really different than the one in the other repo, strange. but it is the same I believe.
> 
> Hmm... 🤔 There were no friction doing the cherry-picks. Maybe you missed the last force push in the original PR?

I was comparing to the merged one :) but it is ok, I decoded it in mem :>

**Comment by alfrunes** [comment]
I had to check by diffing the diffs and nothing changed except for the path names:

<details>
<summary>Diff of diffs</summary>

```diff
--- mono.diff	2024-08-27 10:09:52.419624161 +0200
+++ ../iot-manager/split.diff	2024-08-27 10:10:29.322844575 +0200
@@ -1,7 +1,7 @@
-diff --git a/backend/services/iot-manager/client/iotcore/client.go b/backend/services/iot-manager/client/iotcore/client.go
-index bb7002ed..8d7d3044 100644
---- a/backend/services/iot-manager/client/iotcore/client.go
-+++ b/backend/services/iot-manager/client/iotcore/client.go
+diff --git a/client/iotcore/client.go b/client/iotcore/client.go
+index 8d4a323..604d873 100644
+--- a/client/iotcore/client.go
++++ b/client/iotcore/client.go
 @@ -19,6 +19,7 @@ import (
  	"crypto/ecdsa"
  	"encoding/json"
@@ -155,10 +155,10 @@
  	return &shadow, nil
 -
  }
-diff --git a/backend/services/iot-manager/crypto/csr.go b/backend/services/iot-manager/crypto/csr.go
-index 72c62b91..76d752e4 100644
---- a/backend/services/iot-manager/crypto/csr.go
-+++ b/backend/services/iot-manager/crypto/csr.go
+diff --git a/crypto/csr.go b/crypto/csr.go
+index 72c62b9..76d752e 100644
+--- a/crypto/csr.go
++++ b/crypto/csr.go
 @@ -22,6 +22,7 @@ import (
  	"crypto/x509/pkix"
  	"encoding/pem"
@@ -184,10 +184,10 @@
  }

  func NewCertificateSigningRequest(commonName string, key *ecdsa.PrivateKey) ([]byte, error) {
-diff --git a/backend/services/iot-manager/crypto/csr_test.go b/backend/services/iot-manager/crypto/csr_test.go
-index 03fe168a..4a367b3a 100644
---- a/backend/services/iot-manager/crypto/csr_test.go
-+++ b/backend/services/iot-manager/crypto/csr_test.go
+diff --git a/crypto/csr_test.go b/crypto/csr_test.go
+index 03fe168..4a367b3 100644
+--- a/crypto/csr_test.go
++++ b/crypto/csr_test.go
 @@ -24,9 +24,10 @@ func TestNewPrivateKey(t *testing.T) {
  	key, err := NewPrivateKey()
  	assert.NoError(t, err)
```

</details>

**Comment by merlin-northern** [comment]
> I had to check by diffing the diffs and nothing changed except for the path names:
> 
> Diff of diffs

I know. I went the easier way: I checked by staring.

**Pull request merged**
